#------------------------------------------------------------------------------
#--  Makefile for LEON-3 <> Terrasic DE10 nano Cyclone 5 design
#--  rev. 1.0 : 2020 Provoost Kris
#------------------------------------------------------------------------------
#--  This program is free software: you can redistribute it and/or modify
#--  it under the terms of the GNU General Public License as published by
#--  the Free Software Foundation, either version 3 of the License, or
#--  (at your option) any later version.
#--  This program is distributed in the hope that it will be useful,
#--  but WITHOUT ANY WARRANTY; without even the implied warranty of
#--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#--  GNU General Public License for more details.
#--  You should have received a copy of the GNU General Public License
#--  along with this program.  If not, see <https://www.gnu.org/licenses/>. 
#------------------------------------------------------------------------------


TECHNOLOGY=CYCLONEV
PART=5CSEBA6
PACKAGE=UFBGA
SPEED=-7
SYNFREQ=50
PROMGENPAR=

MANUFACTURER=Altera
MGCPART=$(PART)U23I7
MGCTECHNOLOGY=CycloneV
MGCPACKAGE=UFBGA